### ISSUE TITLE
6.1.6.19. Duomenų pavyzdžiai [1 Etapas]

### ISSUE THREAD

**Issue by TomasLie** [atviriduomenys/katalogas#1344]
> 6.1.6.19. Duomenų pavyzdžiai – turi būti galimybė kiekvienam modeliui ir duomenų laukui pateikti pavyzdinius duomenis, kurie padėtų geriau suprasti duomenų prasmę ir būtų naudojamos generuojant OpenAPI schemas. Pavyzdiniai duomenys taip pat bus naudojami kuriant prieigos teises objekto lygmeniu, testuojant, ar teisingai veikia filtrai. Pavyzdiniai duomenys taip pat bus naudojami užpildant testavimui skirtą API aplinką duomenimis.

---

```yaml
---
# Modelio pilnas kodinis pavadinimas (dataset + / + model)
_type: datasets/gov/example/City
# _id generavimui galima naudoti: https://uuidgen.org/v/4
_id: ca117a8a-fdd0-4c66-9565-093d4d493e6b
name: Vilnius
country:
  _id: dac60010-9a29-4201-8da9-e624023eb626
  name: Lietuva
---
_type: datasets/gov/example/Country
_id: dac60010-9a29-4201-8da9-e624023eb626
name: Lietuva
---
_type: datasets/gov/example/City
_id: bc193575-6747-4104-8bc8-32e88f003ee8
name: Kaunas
country:
  _id: dac60010-9a29-4201-8da9-e624023eb626
  name: Lietuva
```

---
## Reikalavimai

Katalogo pusėje, turi būti galimybė pateikti ir peržiūrėti testinius duomenis, pavyzdžiui:

![Image](https://github.com/user-attachments/assets/4eba9e88-51b2-496e-9229-e31cff872604)

-- https://data.gov.lt/datasets/460/api/getall/AtliekuSusidarymasTvarkymas/

Tikslas, atvaizduoti duomenis, kaip, kaip jie atrodytu darant realias užklausas per API.

Dabar ADP atveju, daroma reali API užklausa ir grąžinamas pirmas rezultatas. Uždarų duomenų atveju, mes neturėsim prieigos per API, todėl galima pasileisti specialų Spinto instance, kuriame būtų suimportuoti testiniai duomenys iš YAML failų.

Importuojant iš YAML failų, testinius duomenis, turi būti patikrinamo klaidos, ar nėra klaidų duomenyse, taikomi tie patys reikalavimai kaip ir 

- https://github.com/atviriduomenys/spinta/issues/1078

--- 
#### 2. Funkcijos turėtu priimti:
- YAML failo path
- DSA arba jo identifikatoriu saugykloje
- Backend kuris perrašytu resource nurodytame DSA, jei MemoryBackend kaip numatytasis jei nenurodyta.
#### 5. Memory backend nėra išbaigtas - todėl tektu tobulinti implementacija, kad padengti esamus poreikius. Galimas sprednimas būtu pernaudoti dataframe funkcionalumą.

Turėtu veikti tokia komanda:

    spinta run dsa.csv -b memory -dsn path/to/example.yml

Ši komanda atidarytu localhost:8000 portą, kuriame matytume path/to/data.yml duomenis, per UDTS.

Papildomai, testavimui nauja komanda, kuri išveda duomenis:

```sh
spinta getall dsa.csv -bt memory -b example.yml
spinta getone dsa.csv -bt memory -b example.yml
```

Kurioje yra naujas argumentas - `-bt` kuris norodo backend tipą, nes šiuo metu `-b` (backend) atitinka dsn prasmę.

### Susiję

- https://github.com/atviriduomenys/katalogas/issues/1408
- https://github.com/atviriduomenys/katalogas/issues/1402
- https://github.com/atviriduomenys/katalogas/issues/1409
