### ISSUE TITLE
6.1.6.28. Duomenų peržiūra

### ISSUE THREAD

**Issue by TomasLie** [atviriduomenys/katalogas#1408]
6.1.6.28. Duomenų peržiūra - (dalinai įgyvendinta) duomenų išteklio duomenų peržiūra kataloge, per UDTS API, su galimybe atlikti duomenų atranką, filtruoti duomenis pagal pasirinktus kriterijus ir atsisiųsti duomenų išranką pasirinktu (CSV, JSON, XML) formatu. Duomenų peržiūra galima tik turint reikiamas prieigos prie duomenų teises, jei tokių reikia. Turi būti galimybė pasirinkti  duomenų šaltinį - vidinius [P1], išorinius [A2] API vartus ir jų gamybines ar testavimo aplinkas.
#

Atlikta analizė: 
- https://github.com/atviriduomenys/dvms/issues/522
---

### 3. Duomenų atvaizdavimas naudojant Spintos funkciją (paspaudus API arba Duomenų skilčių)
Toks YAML kaip šaltinis:
```yaml
---
# Modelio pilnas kodinis pavadinimas (dataset + / + model)
_type: datasets/gov/example/City
# _id generavimui galima naudoti: https://uuidgen.org/v/4
_id: ca117a8a-fdd0-4c66-9565-093d4d493e6b
name: Vilnius
country:
  _id: dac60010-9a29-4201-8da9-e624023eb626
  name: Lietuva
---
_type: datasets/gov/example/Country
_id: dac60010-9a29-4201-8da9-e624023eb626
name: Lietuva
---
_type: datasets/gov/example/City
_id: bc193575-6747-4104-8bc8-32e88f003ee8
name: Kaunas
country:
  _id: dac60010-9a29-4201-8da9-e624023eb626
  name: Lietuva
```

Su tokiu DSA:

```
+----+----------------------+----------+------+---------+----------+---------+-----+---------+---------+-------+--------+
| id | dataset              | resource | base | model   | property | type    | ref | source  | prepare | level | access |
+----+----------------------+----------+------+---------+----------+---------+-----+---------+---------+-------+--------+
|    | datasets/gov/example |          |      |         |          |         |     |         |         |       |        |
|    |                      | spinta   |      |         |          |         |     |         |         |       |        |
|    |                      |          |      |         |          |         |     |         |         |       |        |
|    |                      |          |      | City    |          |         | id  |         |         |       | open   |
|    |                      |          |      |         | _id      | integer |     | _id     |         |       |        |
|    |                      |          |      |         | name     | string  |     | name    |         |       |        |
|    |                      |          |      |         | country  | ref     |     | Country |         |       |        |
|    |                      |          |      | Country |          |         | id  |         |         |       | open   |
|    |                      |          |      |         | _id      | integer |     | _id     |         |       |        |
|    |                      |          |      |         | name     | string  |     | name    |         |       |        |
+----+----------------------+----------+------+---------+----------+---------+-----+---------+---------+-------+--------+

```

Turi būti atvaizduojama JSON formatu:

<img width="1373" alt="Image" src="https://github.com/user-attachments/assets/83b2bd21-01b4-45a5-a00d-7291c7681153" />

Visas "konvertavimas" iš YAML šaltinio turi būti tik naudojant Spintos funkcionalumą su tikslu maksimaliai arčiau realybės  imituoti Spintos veikimą.
Spintos turi būti naudojama kaip library (gal būti versijos konfliktų)

### 4. Pavyzdinių duomenų užklausos adresas (URL)

<img width="1383" alt="Image" src="https://github.com/user-attachments/assets/37874ba2-64e7-496b-89df-7516137dd3ae" />

Pavyzdžių atvėju irgi reikia gebėti pateikti veikianti API endpointą kuris gražintu duomenis, net jei kvieti adresas su išroinių įrankiu (pvz postman), tačiau kadangi Spinta naudojama kaip library tokio kaip serviso nebus ir katalogas turėsi įmituoti/pernaudoti Spintos implementaciją kad visos Spintos užklausos eitu į katalogą po url path, pvz:
Jei turim tikra (ne pavyzdini API):
https://get.data.gov.lt/datasets/gov/kauno_m_sav/mokiniai_grupese/Mokinys
Tai analogiškas API, bet su pavyzdiniais duomenim būtu pasiekiamas po katalogo adresu:
https://data.gov.lt/spinta/examples/datasets/gov/kauno_m_sav/mokiniai_grupese/Mokinys

### 5. Duomenų atvaizdavimo servisas (drop-down) iš kur tiekiami duomenys

Kadangi tie patys (to pačio modelio) duomenys gali būti tiekiami iš skirtingu vietų, reikia pasirinkimo varototojui iš kur jis mato duomenys. Galimi servisai:

- Testiniai duomenys - pavyzdys (atsakymas pirmoje iliustrcijoje) yra tiekiamas iš YAML failo  ([1344](https://github.com/atviriduomenys/katalogas/issues/1344))
- Faktiniai duomenys - pavyzdys iš realiu duomenu, taip kaip jau veikia dabar. 
- Vienas arba keli Spintos agentai partnerio platformoje.

Kai atvaizduojami uždarų duomenys - rodomas bus tik YAML pavyzdys.
Galimas atvėjas jog YAML failo nebus sukelta - tada galimybės atvaizduoti API ir Duomenys dalis nėra įmanoma.

TODO atnaujint nuotraukas.
<img width="1358" alt="Image" src="https://github.com/user-attachments/assets/4d93f0ac-88f1-49d5-9d6f-e5dd8eeb3a4c" />

<img width="1091" alt="Image" src="https://github.com/user-attachments/assets/ae5235a9-043e-4b0d-b5a7-9f22a6ba5cb6" />

## Susiję

- https://github.com/atviriduomenys/katalogas/issues/1344
