### ISSUE TITLE
Duomenu pavydziai duomenu laukams

### ISSUE THREAD

**Issue by varzgalys** [atviriduomenys/katalogas#1453]
Pavyzdziai kurie galetu buti naudojami kaip realus duomenys testuojant arba leidziant aplinkas nuo nulio. Gali buti in-memory stored solution (hardcoded forma kodo bazeje).

Duomenu laukams - https://ivpk.github.io/dsa/1.0/tipai.html#module-type , https://ivpk.github.io/dsa/1.0/dimensijos.html#property

```yaml
---
# Modelio pilnas kodinis pavadinimas (dataset + / + model)
_type: datasets/gov/example/City
# _id generavimui galima naudoti: https://uuidgen.org/v/4
_id: ca117a8a-fdd0-4c66-9565-093d4d493e6b
name: Vilnius
country:
  _id: dac60010-9a29-4201-8da9-e624023eb626
  name: Lietuva
---
_type: datasets/gov/example/Country
_id: dac60010-9a29-4201-8da9-e624023eb626
name: Lietuva
---
n_type: datasets/gov/example/City
_id: bc193575-6747-4104-8bc8-32e88f003ee8
name: Kaunas
country:
  _id: dac60010-9a29-4201-8da9-e624023eb626
  name: Lietuva
```
